Chip: component refactorization
Infineon/infineon-design-system-stencil pull request #1441
Opened 2024-08-29 16:24 UTC by akashyeole

By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Impl
Related Issue
#1191

2024-09-04 09:10 UTC, verena-ifx requested changes

2024-09-04 09:10 UTC, verena-ifx commented on packages/components/src/components/chip/chip-item/chip-item.tsx
> +     * Reference to this component.
would also remove all these comments above the variable names, as the variable names should be self explanatory

2024-09-04 09:10 UTC, verena-ifx commented on packages/components/src/components/chip/chip-item/chip-item.tsx
> +     * Listenting for ifxChipItem event to unselect the previously selected Item.
this comment also isnt needed as the function naming tells already

2024-09-04 09:10 UTC, verena-ifx commented on packages/components/src/components/chip/chip-item/chip-item.tsx
> +     * A function extracts and returns the Item label.
comment not need either, as getItemLabel is self explanatory

2024-09-04 09:10 UTC, verena-ifx commented on packages/components/src/components/chip/chip-item/chip-item.tsx
> +     * Toggles the selection of the Chip Item and emits the ifxChipItem event.
same here

2024-09-04 09:10 UTC, verena-ifx commented on packages/components/src/components/chip/chip-item/chip-item.tsx
> +                {/* Checkbox; renders only in 'multi' variant. */}
can you explain the reason for why you use checkbox + label here and what was the advantage over using multiselect for example?

2024-09-04 09:10 UTC, verena-ifx commented on packages/components/src/components/chip/chip.tsx
> +     * Listening to ifxChipItem event to update the selected option(s).
remove comment

2024-09-04 09:10 UTC, verena-ifx commented on packages/components/src/components/chip/chip.tsx
> +     * Closing the dropdown menu when clicked outside of it.
remove comment

2024-09-04 09:10 UTC, verena-ifx commented on packages/components/src/components/chip/chip.tsx
> +     * Returns the list of reference to the Chip Items.
this function name also pretty well explains what it does and thus, we dont need the comment

2024-09-04 09:10 UTC, verena-ifx commented on packages/components/src/components/chip/chip.tsx
> +     * Returns the selected option label in *single* variant.
same here

2024-09-04 09:10 UTC, verena-ifx commented on packages/components/src/components/chip/chip.tsx
> +     * Opens or Closes the dropdown menu.
and here

2024-09-04 10:05 UTC, akashyeole commented
> The way the chip component's dropdown (the checkbox+label class) is implemented, it gets hidden behind other components, when opened.

Which other components for example?
I tried placing button, badge and accordion below chip and dropdown is always on the top these components.

2024-09-04 10:07 UTC, verena-ifx commented
One more comment @akashyeole could you rename the custom event that is emitted to ifxChipItemSelect or something like that?

2024-09-04 10:08 UTC, verena-ifx commented
> > The way the chip component's dropdown (the checkbox+label class) is implemented, it gets hidden behind other components, when opened.
> 
> Which other components for example? I tried placing button, badge and accordion below chip and dropdown is always on the top these components.

I used it inside the advanced table, but let me clarify with the designers first if you should even be able to open it, as your filters are in the sidebar and thats where you select. in theory :D
![image](https://github.com/user-attachments/assets/9f3f7cba-9485-4df4-8dfb-4aa168a35a74)

2024-09-04 10:19 UTC, verena-ifx commented
> @verena-ifx 'Deploy canary releases and update example apps on...' check is still failing after removing node-sass from dependencies. I don't it has anything to do with node-sass.

when i checked before i saw the working directory wasnt clean. This normally gets solved by a clean install though

2024-09-04 10:25 UTC, verena-ifx commented
@akashyeole I just discussed this regarding the design when used within the table. I think it makes sense to add an additional property "readonly". When set to true, the dropdown menu wont open and it will only show the selected items (which are selected from the table filter)
But let me get some further information first :)

2024-09-06 10:28 UTC, tishoyanchev commented
@akashyeole 
- Rename event name ifxChipChange to ifxChange for consistency

2024-09-06 11:22 UTC, akashyeole commented
> @akashyeole
> 
> * Rename event name ifxChipChange to ifxChange for consistency

It was 'ifxChange' before, Verena changed it as she mentioned it in the comment.
But I also think that it should be 'ifxChange'.  @verena-ifx thoughts?

2024-09-06 15:37 UTC, verena-ifx commented
> > @akashyeole
> > 
> > * Rename event name ifxChipChange to ifxChange for consistency
> 
> It was 'ifxChange' before, Verena changed it as she mentioned it in the comment. But I also think that it should be 'ifxChange'. @verena-ifx thoughts?

mhh for select and multiselect we have ifxSelect. So its not ifxChange for all the components right now. Which benefits do you see in having it ifxchange? I think if we wanna be more unanimous, we should go through all the components and classify them. But before that maybe look at other design systems?

2024-09-09 08:53 UTC, akashyeole commented on packages/components/src/components/chip/chip.tsx
> +            <div class='wrapper__unselect-button' onClick={(e) => { this.handleUnselectButtonClick(e) }}>
@verena-ifx can you add readOnly check for onClick on this line?

2024-09-10 10:02 UTC, tishoyanchev commented
@verena-ifx 
- Can you rename the event name ifxChipChange to ifxChange for consistency?
- The number indicator showing the remaining selected options is not working correctly. I have 4 items. When I select 3, all 3 are shown + the number indicator is showing "+1", indicating that there is one more selected item that is not shown despite that not being the case. If I select all 4, all 4 are displayed, and the number indicator is showing "+2", despite there not being 2 more options selected. All selected options are always displayed, but after the 3rd one, they're also shown in the number indicator. Pic related: 
<img width="511" alt="chip issue 1" src="https://github.com/user-attachments/assets/3ed935ad-d411-47e7-bab9-5fa281ef7e56">
- Cannot run application in the example apps. 
React error: 
<img width="463" alt="react error" src="https://github.com/user-attachments/assets/6d95430b-df1a-4c02-9924-8e7235580540">
Chip not included in Vue and Vanilla-cdn

2024-09-10 10:38 UTC, akashyeole commented
> @verena-ifx
> 
> * Can you rename the event name ifxChipChange to ifxChange for consistency?
> * The number indicator showing the remaining selected options is not working correctly. I have 4 items. When I select 3, all 3 are shown + the number indicator is showing "+1", indicating that there is one more selected item that is not shown despite that not being the case. If I select all 4, all 4 are displayed, and the number indicator is showing "+2", despite there not being 2 more options selected. All selected options are always displayed, but after the 3rd one, they're also shown in the number indicator. Pic related:
> 
> <img alt="chip issue 1" width="511" src="https://private-user-images.githubusercontent.com/108734092/365971368-3ed935ad-d411-47e7-bab9-5fa281ef7e56.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjQzOTgsIm5iZiI6MTcyNTk2NDA5OCwicGF0aCI6Ii8xMDg3MzQwOTIvMzY1OTcxMzY4LTNlZDkzNWFkLWQ0MTEtNDdlNy1iYWI5LTVmYTI4MWVmN2U1Ni5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMDI4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2U0NjJiNzI2YzRlYTVhMjY3MzY5NjE3ZmU5OGEwMTVjM2RiZDFiMmVkYWQyNTk3MmJiYTk1Yzk2OGU4M2I1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AjBpuJ3G0BISZccjtDxefVarOvjlse_AddJ8ZZ5hALg"> - Cannot run application in the example apps. React error: <img alt="react error" width="463" src="https://private-user-images.githubusercontent.com/108734092/365989373-6d95430b-df1a-4c02-9924-8e7235580540.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjQzOTgsIm5iZiI6MTcyNTk2NDA5OCwicGF0aCI6Ii8xMDg3MzQwOTIvMzY1OTg5MzczLTZkOTU0MzBiLWRmMWEtNGMwMi05OTI0LThlNzIzNTU4MDU0MC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMDI4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjFiZTU1YzBlZDlmYWIyMmMzOGZmNWYxZTM0NDdiNGJjZjNiNzgzMWQwNGQ3NjE2MzUyMmIwNjhlMmFkZTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TOHdPcX2hQeBvUKW0gqura5XeX4YOdvH2gjiNHEAZdI"> Chip not included in Vue and Vanilla-cdn

@verena-ifx 

In chip.tsx, on line:198, you should use the this.getSelectedOptions() function. This function handles the joining of selected options and returns at max 2 selected options.

2024-09-11 04:57 UTC, akashyeole commented on packages/components/src/components/chip/chip.tsx
> +            <div class='wrapper__unselect-button' onClick={(e) => { this.handleUnselectButtonClick(e) }}>
@verena-ifx 
Bug: Selected options get unselected when `readOnly` is set and cross button is clicked in multi variant.

https://github.com/user-attachments/assets/00ab1da6-123d-4773-ae89-dc7fb2699ca0

Please readOnly prop check for onClick on line 218.

2024-09-11 13:21 UTC, verena-ifx commented
> > @verena-ifx
> > 
> > * Can you rename the event name ifxChipChange to ifxChange for consistency?
> > * The number indicator showing the remaining selected options is not working correctly. I have 4 items. When I select 3, all 3 are shown + the number indicator is showing "+1", indicating that there is one more selected item that is not shown despite that not being the case. If I select all 4, all 4 are displayed, and the number indicator is showing "+2", despite there not being 2 more options selected. All selected options are always displayed, but after the 3rd one, they're also shown in the number indicator. Pic related:
> > 
> > <img alt="chip issue 1" width="511" src="https://private-user-images.githubusercontent.com/108734092/365971368-3ed935ad-d411-47e7-bab9-5fa281ef7e56.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjQzOTgsIm5iZiI6MTcyNTk2NDA5OCwicGF0aCI6Ii8xMDg3MzQwOTIvMzY1OTcxMzY4LTNlZDkzNWFkLWQ0MTEtNDdlNy1iYWI5LTVmYTI4MWVmN2U1Ni5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMDI4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2U0NjJiNzI2YzRlYTVhMjY3MzY5NjE3ZmU5OGEwMTVjM2RiZDFiMmVkYWQyNTk3MmJiYTk1Yzk2OGU4M2I1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AjBpuJ3G0BISZccjtDxefVarOvjlse_AddJ8ZZ5hALg"> - Cannot run application in the example apps. React error: <img alt="react error" width="463" src="https://private-user-images.githubusercontent.com/108734092/365989373-6d95430b-df1a-4c02-9924-8e7235580540.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjQzOTgsIm5iZiI6MTcyNTk2NDA5OCwicGF0aCI6Ii8xMDg3MzQwOTIvMzY1OTg5MzczLTZkOTU0MzBiLWRmMWEtNGMwMi05OTI0LThlNzIzNTU4MDU0MC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMDI4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjFiZTU1YzBlZDlmYWIyMmMzOGZmNWYxZTM0NDdiNGJjZjNiNzgzMWQwNGQ3NjE2MzUyMmIwNjhlMmFkZTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TOHdPcX2hQeBvUKW0gqura5XeX4YOdvH2gjiNHEAZdI"> Chip not included in Vue and Vanilla-cdn
> 
> @verena-ifx
> 
> In chip.tsx, on line:198, you should use the this.getSelectedOptions() function. This function handles the joining of selected options and returns at max 2 selected options.

regarding the event naming, i thnk that should be a separate issue, because we dont have consistent event naming right now. this PR is already too big cause of the outdated stencil output target dependencies :/

2024-09-12 13:15 UTC, tishoyanchev commented
@akashyeole, @verena-ifx 
- If placeholder is not set, the colons remains. Pic related: 
<img width="191" alt="chip placeholder" src="https://github.com/user-attachments/assets/003d9d82-c271-4a4a-916c-660d4d3e73df">
- In storybook, read-only page, clicking on the X will unselect all options
-suggestion: when read-only is true, remove the "x" button rather than making it disabled

2024-09-12 14:14 UTC, merged