Feature/search bar
Infineon/infineon-design-system-stencil pull request #80
Opened 2023-03-28 18:05 UTC by verena-ifx

By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Search-bar component added

2023-04-04 12:25 UTC, tishoyanchev requested changes

2023-04-04 12:25 UTC, tishoyanchev commented on src/components/search-input/search-input.scss
> +
I am not sure which part of this SCSS, but something is making the `search-input` larger than it should be when nested inside the `ifx-dropdown` component. The width of the `search-input` inside the search variant of the `dropdown` is `262px`, but in Figma (and the way it was before) is `200px`. 
I was not able to immediately understand where does the extra `width` come from.

2023-04-12 11:40 UTC, verena-ifx commented on src/components/search-bar/search-bar.tsx
> +  @Prop() width: string = '100%';
There are 5 sizes, thats why I added the percentages. I am not sure about the responsiveness tbh. Something that was not 100% clear from the Figma to me

2023-04-12 11:40 UTC, verena-ifx commented on src/components/search-bar/search-bar.tsx
> +            <ifx-icon icon="search-16" onClick={this.handleClick}></ifx-icon>
good point, havent seen that one

2023-04-12 11:42 UTC, verena-ifx commented on src/components/search-bar/search-bar.tsx
> +export class SearchBar {
Search Input is a separate Component that should be used inside of the Search bar. That is the information I received. I do not see any mobile specifications on figma though.

2023-04-17 13:52 UTC, merged